runtime: python37


# vpc_access_connector:
#   name: projects/propane-net-292307/locations/australia-southeast1/connectors/esrconnector

# env_variables:
#   CLOUD_SQL_USERNAME: clouduser
#   CLOUD_SQL_PASSWORD: 12345678ESR
#   CLOUD_SQL_DATABASE_NAME: EnergyStorageRights
#   CLOUD_SQL_HOST: 172.29.96.4:1433
  # CLOUD_SQL_HOST: p776084385477-krd871@gcp-sa-cloud-sql.iam.gserviceaccount.com

# beta_settings:
#   cloud_sql_instances: propane-net-292307:australia-southeast1:energy-storage-rights=tcp:1433

entrypoint: gunicorn -b :$PORT main:app
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

handlers:

# - url: /(.*\.(gif|png|jpg))$
#   static_files: static/\1
#   upload: static/.*\.(gif|png|jpg)$

- url: /static
  static_dir: static


  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto